import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

struct DeltaTime {
    seconds: int,
    minutes: int,
    hours: int,
    days: int,
    running: bool,
}

component Timer inherits Rectangle {
    in property<DeltaTime> time;
    in property<bool> running;

    height: running ? 50px : 0px;
    Text {
        text: "\{time.days}d \{time.hours}h \{time.minutes}m \{time.seconds}s";
    }
}

export component AppWindow inherits Window {
    title: "Countdown Timer";

    width: 300px;
    height: 200px;

    callback start-timer;
    callback add-timer(string);

    in property<string> hint;
    in-out property<[DeltaTime]> timers: [
        { running: false },
    ];

    VerticalBox{
        alignment: start;

        Button {
            text: "Start";
            clicked => {
                root.start-timer();
            }
        }

        HorizontalBox {
            input := TextInput {
                width: 2 * parent.width / 3;
            }

            Button {
                text: "Add";
                clicked => {
                    root.add-timer(input.text);
                }
            }
        }

        Text {
            text: "\{hint}";
        }

        for timer in timers : Timer {
            time: timer;
            running: timer.running;
        }
    }
}
